from __future__ import annotations

from app.models import Agent, AgentState, LabEvent, LabMetrics, MemoryEntry, Player, Point, Task, WorldState


def _memory(text: str, day: int, slot: str, importance: int = 1) -> MemoryEntry:
    return MemoryEntry(text=text, day=day, time_slot=slot, importance=importance)


def build_initial_world() -> WorldState:
    player = Player(
        id="player",
        name="你",
        position=Point(x=5, y=8),
        social_links={},
        daily_actions=[],
    )
    agents = [
        Agent(
            id="lin",
            name="Lin",
            role="空间推理研究员",
            persona="rational",
            specialty="多源空间推理",
            current_task="task-geo-baseline",
            current_location="data_wall",
            position=Point(x=13, y=4),
            state=AgentState(
                mood=66,
                stress=40,
                focus=78,
                energy=72,
                curiosity=71,
                research_skill=75,
                geo_reasoning_skill=67,
            ),
            short_term_memory=[_memory("上午在数据墙前复盘基线误差。", 1, "morning", 2)],
            long_term_memory=[_memory("曾在地图配准实验里靠证据链纠正过全组判断。", 1, "morning", 4)],
            current_activity="正在数据墙前核对空间样本",
            current_bubble="这组证据还不够扎实。",
            status_summary="正在盯紧证据链，状态偏专注。",
            last_interaction="刚开始一天的工作，还没和谁深聊。",
            goals=["把 GeoAI 证据链压实", "减少推理误差", "让结论能经得住追问"],
            taboos=["跳结论", "只凭感觉拍板"],
            allies=["jo"],
            rivals=["kai"],
            desired_resource="evidence",
            current_plan="准备拉 Jo 一起复盘基线误差。",
            social_stance="cooperate",
            sprite_style="scientist_a",
            home_position=Point(x=9, y=3),
            home_label="Lin 的木屋",
        ),
        Agent(
            id="mika",
            name="Mika",
            role="创意研究员",
            persona="creative",
            specialty="假设生成",
            current_task="task-insight",
            current_location="meeting",
            position=Point(x=10, y=10),
            state=AgentState(
                mood=74,
                stress=35,
                focus=62,
                energy=70,
                curiosity=85,
                research_skill=66,
                geo_reasoning_skill=52,
            ),
            short_term_memory=[_memory("早餐后想到把街景线索接进 GeoAI 任务。", 1, "morning", 2)],
            long_term_memory=[_memory("上周深夜闲聊时提出过一次关键的多模态思路。", 1, "morning", 4)],
            current_activity="正在白板边写灵感草图",
            current_bubble="我觉得这里还有怪点子。",
            status_summary="灵感很多，心情轻快，想把问题拧出新角度。",
            last_interaction="还在热机，等着有人来接她的话头。",
            goals=["把非常规线索接进实验", "找到一条出人意料的突破口", "说服别人先试试看"],
            taboos=["点子还没展开就被压掉", "所有人只看稳定不看可能性"],
            allies=["rae"],
            rivals=["jo"],
            desired_resource="attention",
            current_plan="想找人试聊一个新的 GeoAI 侧线。",
            social_stance="cooperate",
            sprite_style="scientist_b",
            home_position=Point(x=11, y=23),
            home_label="Mika 的木屋",
        ),
        Agent(
            id="jo",
            name="Jo",
            role="系统工程师",
            persona="engineering",
            specialty="流程与基础设施",
            current_task="task-pipeline",
            current_location="compute",
            position=Point(x=4, y=3),
            state=AgentState(
                mood=61,
                stress=48,
                focus=84,
                energy=68,
                curiosity=58,
                research_skill=72,
                geo_reasoning_skill=49,
            ),
            short_term_memory=[_memory("早上刚把一条训练流水线补齐了监控。", 1, "morning", 2)],
            long_term_memory=[_memory("曾因为一处缓存 bug 让整轮实验回滚过。", 1, "morning", 3)],
            current_activity="正在计算区检查训练流水线",
            current_bubble="先把 pipeline 跑稳。",
            status_summary="对稳定性盯得很紧，耐心一般但执行力在线。",
            last_interaction="还在埋头看系统，没有真正展开聊天。",
            goals=["先保证系统稳定", "别让训练链路掉线", "把模糊方案变成可执行步骤"],
            taboos=["空谈", "临时改需求却不给时间"],
            allies=["lin"],
            rivals=["mika"],
            desired_resource="compute",
            current_plan="盯住算力和流水线，不想被临时插队。",
            social_stance="compete",
            sprite_style="scientist_a",
            home_position=Point(x=21, y=3),
            home_label="Jo 的木屋",
        ),
        Agent(
            id="rae",
            name="Rae",
            role="实验室协调员",
            persona="empathetic",
            specialty="团队氛围维护",
            current_task="task-sync",
            current_location="lounge",
            position=Point(x=17, y=10),
            state=AgentState(
                mood=82,
                stress=28,
                focus=58,
                energy=76,
                curiosity=64,
                research_skill=54,
                geo_reasoning_skill=44,
            ),
            short_term_memory=[_memory("刚给大家补了咖啡，准备午间同步。", 1, "morning", 2)],
            long_term_memory=[_memory("擅长在组会前把紧张气氛压下来。", 1, "morning", 3)],
            current_activity="正在休闲区整理茶点和便签",
            current_bubble="先别急，慢慢说。",
            status_summary="情绪稳定，正在照看大家的节奏。",
            last_interaction="目前主要在观察大家的状态。",
            goals=["让团队别在关键时刻翻脸", "帮高压成员缓冲情绪", "把分歧导回可谈状态"],
            taboos=["互相消耗", "把问题上升成人身对立"],
            allies=["mika", "kai"],
            rivals=[],
            desired_resource="calm",
            current_plan="随时准备去调停一场快吵起来的争执。",
            social_stance="mediate",
            sprite_style="scientist_b",
            home_position=Point(x=29, y=23),
            home_label="Rae 的木屋",
        ),
        Agent(
            id="kai",
            name="Kai",
            role="外部信号分析员",
            persona="opportunist",
            specialty="趋势感知",
            current_task="task-news",
            current_location="terminal",
            position=Point(x=18, y=3),
            state=AgentState(
                mood=69,
                stress=44,
                focus=56,
                energy=73,
                curiosity=77,
                research_skill=60,
                geo_reasoning_skill=46,
            ),
            short_term_memory=[_memory("信息终端里盯着外部热点和市场波动。", 1, "morning", 2)],
            long_term_memory=[_memory("曾经因为一条突发新闻让全组临时改了议题。", 1, "morning", 3)],
            current_activity="正在信息终端刷 Brave 信号",
            current_bubble="今天外部风向有点意思。",
            status_summary="对外部变化很敏感，脑子里全是下一波信号。",
            last_interaction="一边看热点，一边等值得追的对话。",
            goals=["抢到最有价值的外部信号窗口", "把热点带进实验决策", "别错过可能爆发的时机"],
            taboos=["动作太慢", "证据还没热就被压掉"],
            allies=["rae"],
            rivals=["lin"],
            desired_resource="signal",
            current_plan="想把最新的外部信号塞进今天的议程。",
            social_stance="compete",
            sprite_style="scientist_a",
            home_position=Point(x=38, y=3),
            home_label="Kai 的木屋",
        ),
    ]
    relation_seed = {
        "lin": {"mika": 32, "jo": 58, "rae": 26, "kai": 18, "player": 14},
        "mika": {"lin": 35, "jo": 22, "rae": 54, "kai": 28, "player": 16},
        "jo": {"lin": 56, "mika": 18, "rae": 24, "kai": 12, "player": 10},
        "rae": {"lin": 30, "mika": 57, "jo": 27, "kai": 34, "player": 18},
        "kai": {"lin": 16, "mika": 26, "jo": 14, "rae": 38, "player": 12},
    }
    for agent in agents:
        agent.relations = relation_seed[agent.id]
    tasks = [
        Task(
            id="task-geo-baseline",
            title="GeoAI 基线冲刺",
            category="main",
            description="从对话和外部信息里收集证据，让团队地理推理能力突破 45。",
            progress=28,
            target=100,
            participants=["lin", "jo", "mika"],
            rewards={"geoai_progress": 18, "knowledge_base": 12},
        ),
        Task(
            id="task-sync",
            title="晚间研究同步",
            category="social",
            description="在夜晚前和至少两名同事交流，稳定实验室氛围。",
            progress=15,
            target=100,
            participants=["rae"],
            rewards={"team_atmosphere": 10},
        ),
        Task(
            id="task-news",
            title="外部信号扫描",
            category="external",
            description="注入一条有价值的 Brave 信息，并转成实验室事件。",
            progress=0,
            target=100,
            participants=["kai"],
            rewards={"external_sensitivity": 14, "research_progress": 8},
        ),
    ]
    events = [
        LabEvent(
            id="event-boot",
            category="geoai",
            title="基线地图复盘",
            summary="团队正在复盘当前 GeoAI 基准里的薄弱环节。",
            source="lab",
            time_slot="morning",
            impacts={"collective_reasoning": 3, "knowledge_base": 2},
            participants=["lin", "jo"],
        )
    ]
    lab = LabMetrics(
        reputation=21,
        knowledge_base=32,
        team_atmosphere=68,
        collective_reasoning=34,
        research_progress=27,
        external_sensitivity=22,
        geoai_progress=29,
    )
    return WorldState(
        version=8,
        world_width=44,
        world_height=26,
        day=1,
        time_slot="morning",
        weather="sunny",
        player=player,
        agents=agents,
        tasks=tasks,
        events=events,
        lab=lab,
        ambient_dialogues=[],
        social_threads=[],
        story_beats=[],
    )
