from __future__ import annotations

from app.models import Agent, AgentState, BankState, ConsumableItem, IndexCandle, LabEvent, LabMetrics, MarketState, MemoryEntry, Player, Point, PropertyAsset, StockQuote, Task, WorldState


def _memory(text: str, day: int, slot: str, importance: int = 1) -> MemoryEntry:
    return MemoryEntry(text=text, day=day, time_slot=slot, importance=importance)


def build_initial_world() -> WorldState:
    player = Player(
        id="player",
        name="你",
        position=Point(x=5, y=8),
        cash=100,
        risk_appetite=52,
        life_satisfaction=58,
        consumption_desire=52,
        housing_quality=50,
        materialism=48,
        comfort_preference=62,
        portfolio={},
        last_trade_summary="",
        social_links={},
        daily_actions=[],
        owned_property_ids=["property-player-cottage"],
    )
    agents = [
        Agent(
            id="lin",
            name="林澈",
            role="空间推理研究员",
            persona="rational",
            specialty="多源空间推理",
            current_task="task-geo-baseline",
            current_location="data_wall",
            position=Point(x=13, y=4),
            state=AgentState(
                mood=66,
                stress=40,
                focus=78,
                energy=72,
                curiosity=71,
                research_skill=75,
                geo_reasoning_skill=67,
            ),
            short_term_memory=[_memory("上午在数据墙前复盘基线误差。", 1, "morning", 2)],
            long_term_memory=[_memory("曾在地图配准实验里靠证据链纠正过全组判断。", 1, "morning", 4)],
            current_activity="正在数据墙前核对空间样本",
            current_bubble="这组证据还不够扎实。",
            status_summary="正在盯紧证据链，状态偏专注。",
            last_interaction="刚开始一天的工作，还没和谁深聊。",
            goals=["把 GeoAI 证据链压实", "减少推理误差", "让结论能经得住追问"],
            taboos=["跳结论", "只凭感觉拍板"],
            allies=["jo"],
            rivals=["kai"],
            desired_resource="evidence",
            current_plan="准备拉周铖一起复盘基线误差。",
            social_stance="cooperate",
            sprite_style="scientist_a",
            cash=100,
            money_desire=34,
            generosity=26,
            money_urgency=34,
            credit_score=84,
            risk_appetite=26,
            portfolio={"GEO": 1},
            home_position=Point(x=9, y=3),
            home_label="林澈的小屋",
            life_satisfaction=58,
            consumption_desire=34,
            housing_quality=54,
            materialism=28,
            comfort_preference=52,
            monthly_burden=3,
            owned_property_ids=["property-lin-cottage"],
            core_needs=["把判断建立在硬证据上", "不想让团队被空话带偏"],
            public_facts=["平时说话克制", "很少在没把握时表态", "对周铖的执行力最信任"],
            hidden_facts=["其实很在意自己是否判断失误", "对凯川追热点的方式一直不放心"],
            speech_habits=["嗯", "先别急", "我再核一下"],
        ),
        Agent(
            id="mika",
            name="米遥",
            role="创意研究员",
            persona="creative",
            specialty="假设生成",
            current_task="task-insight",
            current_location="meeting",
            position=Point(x=10, y=10),
            state=AgentState(
                mood=74,
                stress=35,
                focus=62,
                energy=70,
                curiosity=85,
                research_skill=66,
                geo_reasoning_skill=52,
            ),
            short_term_memory=[_memory("早餐后想到把街景线索接进 GeoAI 任务。", 1, "morning", 2)],
            long_term_memory=[_memory("上周深夜闲聊时提出过一次关键的多模态思路。", 1, "morning", 4)],
            current_activity="正在白板边写灵感草图",
            current_bubble="我觉得这里还有怪点子。",
            status_summary="灵感很多，心情轻快，想把问题拧出新角度。",
            last_interaction="还在热机，等着有人来接她的话头。",
            goals=["把非常规线索接进实验", "找到一条出人意料的突破口", "说服别人先试试看"],
            taboos=["点子还没展开就被压掉", "所有人只看稳定不看可能性"],
            allies=["rae"],
            rivals=["jo"],
            desired_resource="attention",
            current_plan="想找人试聊一个新的 GeoAI 侧线。",
            social_stance="cooperate",
            sprite_style="scientist_b",
            cash=100,
            money_desire=57,
            generosity=44,
            money_urgency=57,
            credit_score=71,
            risk_appetite=63,
            portfolio={"AGR": 2},
            home_position=Point(x=11, y=23),
            home_label="米遥的小屋",
            life_satisfaction=63,
            consumption_desire=67,
            housing_quality=48,
            materialism=62,
            comfort_preference=58,
            monthly_burden=2,
            owned_property_ids=["property-mika-cottage"],
            core_needs=["想证明怪点子也能成立", "需要被认真接住而不是被打断"],
            public_facts=["容易发散", "喜欢边走边聊", "和芮宁最聊得来"],
            hidden_facts=["很怕自己被当成只会乱想的人", "被周铖否掉时会嘴硬但会记很久"],
            speech_habits=["诶", "等等", "我突然想到"],
        ),
        Agent(
            id="jo",
            name="周铖",
            role="系统工程师",
            persona="engineering",
            specialty="流程与基础设施",
            current_task="task-pipeline",
            current_location="compute",
            position=Point(x=4, y=3),
            state=AgentState(
                mood=61,
                stress=48,
                focus=84,
                energy=68,
                curiosity=58,
                research_skill=72,
                geo_reasoning_skill=49,
            ),
            short_term_memory=[_memory("早上刚把一条训练流水线补齐了监控。", 1, "morning", 2)],
            long_term_memory=[_memory("曾因为一处缓存 bug 让整轮实验回滚过。", 1, "morning", 3)],
            current_activity="正在计算区检查训练流水线",
            current_bubble="先把 pipeline 跑稳。",
            status_summary="对稳定性盯得很紧，耐心一般但执行力在线。",
            last_interaction="还在埋头看系统，没有真正展开聊天。",
            goals=["先保证系统稳定", "别让训练链路掉线", "把模糊方案变成可执行步骤"],
            taboos=["空谈", "临时改需求却不给时间"],
            allies=["lin"],
            rivals=["mika"],
            desired_resource="compute",
            current_plan="盯住算力和流水线，不想被临时插队。",
            social_stance="compete",
            sprite_style="scientist_a",
            cash=100,
            money_desire=79,
            generosity=18,
            money_urgency=79,
            credit_score=62,
            risk_appetite=48,
            portfolio={"SIG": 2},
            home_position=Point(x=21, y=3),
            home_label="周铖的小屋",
            life_satisfaction=49,
            consumption_desire=29,
            housing_quality=46,
            materialism=24,
            comfort_preference=44,
            monthly_burden=2,
            owned_property_ids=["property-jo-cottage"],
            core_needs=["把事情落到可执行层", "不想替别人收烂尾"],
            public_facts=["说话硬", "最讨厌低效", "习惯先看实现路径"],
            hidden_facts=["其实对失控和返工特别敏感", "累的时候会故意把话说得更冲"],
            speech_habits=["行", "说人话", "先落地"],
        ),
        Agent(
            id="rae",
            name="芮宁",
            role="实验室协调员",
            persona="empathetic",
            specialty="团队氛围维护",
            current_task="task-sync",
            current_location="lounge",
            position=Point(x=17, y=10),
            state=AgentState(
                mood=82,
                stress=28,
                focus=58,
                energy=76,
                curiosity=64,
                research_skill=54,
                geo_reasoning_skill=44,
            ),
            short_term_memory=[_memory("刚给大家补了咖啡，准备午间同步。", 1, "morning", 2)],
            long_term_memory=[_memory("擅长在组会前把紧张气氛压下来。", 1, "morning", 3)],
            current_activity="正在休闲区整理茶点和便签",
            current_bubble="先别急，慢慢说。",
            status_summary="情绪稳定，正在照看大家的节奏。",
            last_interaction="目前主要在观察大家的状态。",
            goals=["让团队别在关键时刻翻脸", "帮高压成员缓冲情绪", "把分歧导回可谈状态"],
            taboos=["互相消耗", "把问题上升成人身对立"],
            allies=["mika", "kai"],
            rivals=[],
            desired_resource="calm",
            current_plan="随时准备去调停一场快吵起来的争执。",
            social_stance="mediate",
            sprite_style="scientist_b",
            cash=100,
            money_desire=23,
            generosity=82,
            money_urgency=23,
            credit_score=88,
            risk_appetite=18,
            portfolio={"AGR": 1},
            home_position=Point(x=29, y=23),
            home_label="芮宁的小屋",
            life_satisfaction=71,
            consumption_desire=42,
            housing_quality=58,
            materialism=34,
            comfort_preference=71,
            monthly_burden=3,
            owned_property_ids=["property-rae-cottage"],
            core_needs=["维持团队情绪稳定", "不想看见关系恶化"],
            public_facts=["会接情绪", "容易当调停者", "观察力很细"],
            hidden_facts=["一直在默默记谁最近最累", "对表面和气但暗里较劲很敏感"],
            speech_habits=["慢慢说", "我在听", "先别绷着"],
        ),
        Agent(
            id="kai",
            name="凯川",
            role="外部信号分析员",
            persona="opportunist",
            specialty="趋势感知",
            current_task="task-news",
            current_location="terminal",
            position=Point(x=18, y=3),
            state=AgentState(
                mood=69,
                stress=44,
                focus=56,
                energy=73,
                curiosity=77,
                research_skill=60,
                geo_reasoning_skill=46,
            ),
            short_term_memory=[_memory("信息终端里盯着外部热点和市场波动。", 1, "morning", 2)],
            long_term_memory=[_memory("曾经因为一条突发新闻让全组临时改了议题。", 1, "morning", 3)],
            current_activity="正在信息终端刷 Brave 信号",
            current_bubble="今天外部风向有点意思。",
            status_summary="对外部变化很敏感，脑子里全是下一波信号。",
            last_interaction="一边看热点，一边等值得追的对话。",
            goals=["抢到最有价值的外部信号窗口", "把热点带进实验决策", "别错过可能爆发的时机"],
            taboos=["动作太慢", "证据还没热就被压掉"],
            allies=["rae"],
            rivals=["lin"],
            desired_resource="signal",
            current_plan="想把最新的外部信号塞进今天的议程。",
            social_stance="compete",
            sprite_style="scientist_a",
            cash=100,
            money_desire=88,
            generosity=22,
            money_urgency=88,
            credit_score=58,
            risk_appetite=81,
            portfolio={"SIG": 1, "GEO": 1},
            home_position=Point(x=38, y=3),
            home_label="凯川的小屋",
            life_satisfaction=52,
            consumption_desire=74,
            housing_quality=44,
            materialism=72,
            comfort_preference=40,
            monthly_burden=2,
            owned_property_ids=["property-kai-cottage"],
            core_needs=["别错过外部窗口", "想成为最先嗅到变化的人"],
            public_facts=["消息灵", "喜欢看风向", "总想把外部信号带进来"],
            hidden_facts=["很怕自己慢一步就被证明没价值", "其实一直想做出一次真正关键的判断"],
            speech_habits=["哎", "有点意思", "我闻到点动静"],
        ),
    ]
    relation_seed = {
        "lin": {"mika": 32, "jo": 58, "rae": 26, "kai": 18, "player": 14},
        "mika": {"lin": 35, "jo": 22, "rae": 54, "kai": 28, "player": 16},
        "jo": {"lin": 56, "mika": 18, "rae": 24, "kai": 12, "player": 10},
        "rae": {"lin": 30, "mika": 57, "jo": 27, "kai": 34, "player": 18},
        "kai": {"lin": 16, "mika": 26, "jo": 14, "rae": 38, "player": 12},
    }
    for agent in agents:
        agent.relations = relation_seed[agent.id]
    tasks = [
        Task(
            id="task-geo-baseline",
            title="团队资金扩张",
            category="main",
            description="把团队总现金从 $500 推到更高，靠明确借贷、日常协作和白天兑现收益慢慢做大。",
            progress=0,
            target=100,
            participants=["lin", "jo", "mika", "rae", "kai"],
            rewards={"reputation": 10, "knowledge_base": 6},
        ),
        Task(
            id="task-sync",
            title="晚间研究同步",
            category="social",
            description="在夜晚前和至少两名同事交流，稳定实验室氛围。",
            progress=15,
            target=100,
            participants=["rae"],
            rewards={"team_atmosphere": 10},
        ),
        Task(
            id="task-news",
            title="外部信号扫描",
            category="external",
            description="注入一条有价值的 Brave 信息，并转成实验室事件。",
            progress=0,
            target=100,
            participants=["kai"],
            rewards={"external_sensitivity": 14, "research_progress": 8},
        ),
    ]
    events = [
        LabEvent(
            id="event-boot",
            category="geoai",
            title="基线地图复盘",
            summary="团队正在复盘当前 GeoAI 基准里的薄弱环节。",
            source="lab",
            time_slot="morning",
            impacts={"collective_reasoning": 3, "knowledge_base": 2},
            participants=["lin", "jo"],
        )
    ]
    lab = LabMetrics(
        reputation=21,
        knowledge_base=32,
        team_atmosphere=68,
        collective_reasoning=34,
        research_progress=27,
        external_sensitivity=22,
        geoai_progress=29,
    )
    market = MarketState(
        name="Pixel Exchange",
        is_open=True,
        sentiment=6,
        tick=0,
        regime="bull",
        regime_age=1,
        rotation_leader="GEO",
        rotation_age=1,
        index_value=100.0,
        stocks=[
            StockQuote(symbol="GEO", name="GeoGrid", sector="geoai", price=24.0, open_price=24.0, last_reason="开盘平稳"),
            StockQuote(symbol="AGR", name="AgriLoop", sector="daily", price=18.0, open_price=18.0, last_reason="天气稳定"),
            StockQuote(symbol="SIG", name="SignalWorks", sector="signal", price=31.0, open_price=31.0, last_reason="外部消息面偏热"),
        ],
        index_history=[IndexCandle(day=1, open=100.0, high=100.0, low=100.0, close=100.0, limit_state="normal")],
        daily_index_history=[IndexCandle(day=1, open=100.0, high=100.0, low=100.0, close=100.0, limit_state="normal")],
    )
    bank = BankState(
        name="青松合作银行",
        liquidity=1800,
        base_daily_rate_pct=2.0,
        risk_spread_pct=0.2,
        total_issued=0,
        total_repaid=0,
        defaults_count=0,
    )
    lifestyle_catalog = [
        ConsumableItem(
            id="coffee-run",
            name="手冲咖啡",
            category="food",
            price=6,
            description="提神的小消费，适合白天补状态。",
            satisfaction_gain=4,
            mood_gain=3,
            energy_gain=6,
            relation_bonus=1,
            debt_eligible=False,
            giftable=True,
        ),
        ConsumableItem(
            id="warm-lunch",
            name="热饭套餐",
            category="food",
            price=10,
            description="能明显补体力，适合中午或傍晚。",
            satisfaction_gain=6,
            mood_gain=2,
            energy_gain=10,
            relation_bonus=1,
            debt_eligible=True,
            giftable=True,
        ),
        ConsumableItem(
            id="flower-gift",
            name="花束礼物",
            category="gift",
            price=14,
            description="适合送人，偏重关系和满意度。",
            satisfaction_gain=5,
            mood_gain=3,
            relation_bonus=4,
            debt_eligible=True,
            giftable=True,
        ),
        ConsumableItem(
            id="soft-lamp",
            name="柔光台灯",
            category="comfort",
            price=22,
            description="改善居住舒适度的小件家具。",
            satisfaction_gain=7,
            mood_gain=2,
            comfort_gain=8,
            debt_eligible=True,
        ),
        ConsumableItem(
            id="garden-toolkit",
            name="园艺工具包",
            category="tool",
            price=18,
            description="提升生活与地产维护体验。",
            satisfaction_gain=4,
            mood_gain=1,
            comfort_gain=4,
            debt_eligible=True,
        ),
    ]
    properties = [
        PropertyAsset(
            id="property-player-cottage",
            owner_type="player",
            owner_id="player",
            property_type="home_upgrade",
            name="你的木屋",
            position=Point(x=6, y=22),
            width=2,
            height=2,
            purchase_price=48,
            estimated_value=58,
            daily_income=0,
            daily_maintenance=2,
            comfort_bonus=8,
            social_bonus=1,
            debt_eligible=True,
            listed=False,
            built=True,
            status="owned",
            description="你目前的小屋，会影响休息体验和生活满意度。",
        ),
        PropertyAsset(id="property-lin-cottage", owner_type="agent", owner_id="lin", property_type="home_upgrade", name="林澈的小屋", position=Point(x=9, y=2), purchase_price=46, estimated_value=55, daily_maintenance=2, comfort_bonus=6, social_bonus=0, debt_eligible=True, listed=False, built=True, status="owned", description="证据控偏简洁的居住空间。"),
        PropertyAsset(id="property-mika-cottage", owner_type="agent", owner_id="mika", property_type="home_upgrade", name="米遥的小屋", position=Point(x=11, y=22), purchase_price=44, estimated_value=53, daily_maintenance=2, comfort_bonus=7, social_bonus=1, debt_eligible=True, listed=False, built=True, status="owned", description="色彩更活、装饰更跳的个人空间。"),
        PropertyAsset(id="property-jo-cottage", owner_type="agent", owner_id="jo", property_type="home_upgrade", name="周铖的小屋", position=Point(x=21, y=2), purchase_price=45, estimated_value=56, daily_maintenance=2, comfort_bonus=5, social_bonus=0, debt_eligible=True, listed=False, built=True, status="owned", description="偏功能化的小屋。"),
        PropertyAsset(id="property-rae-cottage", owner_type="agent", owner_id="rae", property_type="home_upgrade", name="芮宁的小屋", position=Point(x=29, y=22), purchase_price=47, estimated_value=59, daily_maintenance=2, comfort_bonus=8, social_bonus=2, debt_eligible=True, listed=False, built=True, status="owned", description="更适合休息和待客的小屋。"),
        PropertyAsset(id="property-kai-cottage", owner_type="agent", owner_id="kai", property_type="home_upgrade", name="凯川的小屋", position=Point(x=38, y=2), purchase_price=45, estimated_value=54, daily_maintenance=2, comfort_bonus=5, social_bonus=1, debt_eligible=True, listed=False, built=True, status="owned", description="靠近外部风向的小屋。"),
        PropertyAsset(
            id="property-farm-north",
            owner_type="market",
            owner_id="market",
            property_type="farm_plot",
            name="北侧试验农田",
            position=Point(x=14, y=14),
            width=3,
            height=3,
            purchase_price=64,
            estimated_value=64,
            daily_income=6,
            daily_maintenance=1,
            comfort_bonus=2,
            social_bonus=1,
            debt_eligible=True,
            listed=True,
            built=True,
            status="listed",
            description="稳定产出型农田，收益低但很稳。",
        ),
        PropertyAsset(
            id="property-rental-lakeside",
            owner_type="market",
            owner_id="market",
            property_type="rental_house",
            name="湖边出租屋",
            position=Point(x=34, y=19),
            width=2,
            height=2,
            purchase_price=88,
            estimated_value=88,
            daily_income=9,
            daily_maintenance=3,
            comfort_bonus=5,
            social_bonus=3,
            debt_eligible=True,
            listed=True,
            built=True,
            status="listed",
            description="租金更高，但维护和口碑更敏感。",
        ),
        PropertyAsset(
            id="property-shop-orchard",
            owner_type="market",
            owner_id="market",
            property_type="shop",
            name="果园小店铺",
            position=Point(x=35, y=8),
            width=2,
            height=2,
            purchase_price=112,
            estimated_value=112,
            daily_income=12,
            daily_maintenance=4,
            comfort_bonus=1,
            social_bonus=4,
            debt_eligible=True,
            listed=True,
            built=True,
            status="listed",
            description="收益更高，但更吃口碑和天气。",
        ),
        PropertyAsset(
            id="property-greenhouse-lot",
            owner_type="market",
            owner_id="market",
            property_type="greenhouse",
            name="空置温室地块",
            position=Point(x=23, y=18),
            width=3,
            height=2,
            purchase_price=96,
            estimated_value=96,
            daily_income=10,
            daily_maintenance=3,
            comfort_bonus=3,
            social_bonus=2,
            debt_eligible=True,
            buildable=True,
            listed=True,
            built=False,
            status="listed",
            description="可以直接建成温室，兼具收益和舒适度。",
        ),
    ]
    return WorldState(
        version=24,
        world_width=44,
        world_height=26,
        day=1,
        time_slot="morning",
        weather="sunny",
        player=player,
        agents=agents,
        tasks=tasks,
        events=events,
        lab=lab,
        market=market,
        bank=bank,
        archived_tasks=[],
        ambient_dialogues=[],
        dialogue_history=[],
        geoai_milestones=[],
        daily_briefings=[],
        social_threads=[],
        story_beats=[],
        loans=[],
        bank_loans=[],
        gray_cases=[],
        lifestyle_catalog=lifestyle_catalog,
        properties=properties,
        finance_history=[],
    )
